version: 2
updates:
- package-ecosystem: pip
  directory: "/ksweb"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ming
    versions:
    - 0.10.2
